import "./globals.css";
import type { Metadata } from "next";
import { Provider } from "./providers";
import Navbar from "../components/Navbar";
import "@uploadthing/react/styles.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Provider>
          {/* <Navbar /> */}
          {children}
        </Provider>
      </body>
    </html>
  );
}
