import "./globals.css";
import type { Metadata } from "next";
import { Provider } from "./providers";
import Navbar from "../components/Navbar";
import "@uploadthing/react/styles.css";
import StarterAnimation from "@/components/StarterAnimation";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Provider>
          {/* <Navbar /> */}
          <div className="w-full h-full relative">
            {/* <StarterAnimation /> */}
            <div className="relative top-0 left-0 w-full h-full">
              <Navbar />
              {children}
            </div>
          </div>
        </Provider>
      </body>
    </html>
  );
}
