import "./globals.css";
import type { Metadata } from "next";
import { Provider } from "./providers";
import Navbar from "../components/Navbar";
import "@uploadthing/react/styles.css";
import AnimationContext from "@/components/WaltDisney/AnimationContext";
import AnimationController from "@/components/WaltDisney/AnimationController";
import { useContext } from "react";
import Content from "@/components/Content";
import { getServerSession } from "next-auth";
import { authOptions } from "./api/auth/[...nextauth]/route";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Provider>
          <AnimationController>
            <Content>{children}</Content>
          </AnimationController>
        </Provider>
      </body>
    </html>
  );
}
